version = 1

test_patterns = ["src/__tests__/**"]

exclude_patterns = ["dist/*.map"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser"
  ]
  dialect = "typescript"
  plugins = ["react"]