dist: focal
language: node_js
node_js:
    - 18
cache:
    npm: false
    directories:
        - "~/.pnpm-store"
before_install:
    - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7.18.2
    - pnpm config set store-dir ~/.pnpm-store
install:
    - pnpm install
scripts:
    - pnpm test:ci
