dist: focal
language: node_js
node_js:
    - stable
cache:
    npm: false
    directories:
        - "~/.pnpm-store"
before_install:
    - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@6.32.24
    - pnpm config set store-dir ~/.pnpm-store
install:
    - pnpm install
scripts:
    - pnpm nx test:ci core
